term.clear()
term.setCursorPos(1,1)
term.setTextColor( colors.green )
print("*** EnderTank Assignments ****")
print("astrocreep - dark blue | light blue")
print("majorbestage - green | yellow")
print("capuel - blue | black")
print("")

local event, key = os.pullEvent( "key" )
os.run({}, "nosnet/ComputerCraft/nosmenu.lua")
